apiVersion: v1
kind: Secret
metadata:
  name: os-service-secret
  labels:
    app.kubernetes.io/name: os-service
    app.kubernetes.io/part-of: fiap-tech-challenge
type: Opaque
stringData:
  JWT_SECRET: "replace-with-jwt-secret"
  DB_USERNAME: "replace-with-db-username"
  DB_PASSWORD: "replace-with-db-password"
