apiVersion: v1
kind: Secret
metadata:
  name: os-service-secret
  labels:
    app.kubernetes.io/name: os-service
    app.kubernetes.io/part-of: fiap-tech-challenge
type: Opaque
stringData:
  JWT_SECRET: "${JWT_SECRET}"
  DB_USERNAME: "${OS_DB_USERNAME}"
  DB_PASSWORD: "${OS_DB_PASSWORD}"
