apiVersion: v1
kind: Service
metadata:
  name: os-service
  labels:
    app.kubernetes.io/name: os-service
    app.kubernetes.io/part-of: fiap-tech-challenge
spec:
  selector:
    app.kubernetes.io/name: os-service
  ports:
    - name: http
      port: 80
      targetPort: http
  type: ClusterIP
